### ISSUE TITLE
No location detected when killing an application on Android 10

### ISSUE THREAD

**Issue by Adigezalov** [darron1217/react-native-background-geolocation#1]
Location is not detected when the application is killed
At startup I select "Allow all" on dialog

Android 10
RN 0.63.3

**Comment by darron1217** [comment]
What you mean `Location is not detected`?
You mean `BackgroundGeolocation.on('location', (location) => {` callback or POST request with `postTemplate`?

**Comment by Adigezalov** [comment]
Yes. The BackgroundGeolocation.on ('location', (location) => {callback} callback only works if the application is running or in the background.
As soon as the application turns off, the icon remains lit in the tray that geolocation is working, but in fact the coordinates are not collected.

**Comment by darron1217** [comment]
@Adigezalov That's normal behavior.
You should use `url`, `httpHeaders`, `postTemplate` to keep track on location change even your app is terminated.
(Which means you need server to receive background POST requests)

**Comment by Adigezalov** [comment]
@darron1217 Hmm ... for some reason I thought it should update locally when turned off. Thanks for the answer! I will redo =)
But then the next question arises. How to turn off the geolocation service after a specified period of time when the app is turned off?

**Comment by darron1217** [comment]
@Adigezalov 
You can check the manual 

Android headless task
https://github.com/darron1217/react-native-background-geolocation#android-headless-task-experimental

IOS background task
https://github.com/darron1217/react-native-background-geolocation#quick-example
```
    BackgroundGeolocation.on('location', (location) => {
      // handle your locations here
      // to perform long running operation on iOS
      // you need to create background task
      BackgroundGeolocation.startTask(taskKey => {
        // execute long running task
        // eg. ajax post location
        // IMPORTANT: task has to be ended by endTask
        BackgroundGeolocation.endTask(taskKey);
      });
    });
```

**Comment by darron1217** [comment]
Or you can use paid version.
There's `stopAfterElapsedMinutes` option.
https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#geolocation-options

**Comment by zoobibackups** [comment]
> @Adigezalov
> You can check the manual
> 
> Android headless task
> https://github.com/darron1217/react-native-background-geolocation#android-headless-task-experimental
> 
> IOS background task
> https://github.com/darron1217/react-native-background-geolocation#quick-example
> 
> ```
>     BackgroundGeolocation.on('location', (location) => {
>       // handle your locations here
>       // to perform long running operation on iOS
>       // you need to create background task
>       BackgroundGeolocation.startTask(taskKey => {
>         // execute long running task
>         // eg. ajax post location
>         // IMPORTANT: task has to be ended by endTask
>         BackgroundGeolocation.endTask(taskKey);
>       });
>     });
> ```

Not working in headless task, only works for about 10s then nothing works in background
