### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by ydeshayes** [darron1217/react-native-background-geolocation#10]
Hello,

I saw https://github.com/darron1217/background-geolocation-android/compare/d54617d71f167fd72a0a33172fd6ff43c6ae0251...7a1d3c6d3c83305b953dca7f005a5f8800787472#diff-6305bbf50570f0946de077f04e8ea56c53d8f6e1b53ec403c8c2ddb10d531db1 

Why did you reverted the changes and what can we do to support android 10 then please?

Thanks for your help

**Comment by darron1217** [comment]
@ydeshayes The link shows nothing to compare. Please check url

**Comment by ydeshayes** [comment]
Sorry, after reading the android 10 changes, I guess the real fix is https://github.com/darron1217/react-native-background-geolocation/commit/1c58c10a03072be87073e5083c75dbb1c3a7828b thx!
