### ISSUE TITLE
Plugin is not working for Android 10 on real device.

### ISSUE THREAD

**Issue by ShooterArk** [darron1217/react-native-background-geolocation#3]
## Your Environment

* Plugin version: 0.6.4
* Platform: Android
* OS version: 10
* Device manufacturer and model: Samsung A71

## Context
I switched from main geolocation library to this one and was successful to integrate it properly. I didnt face any issue when running the app on emulator but when I executed the same application on my real device, its not posting the latitudes and longitudes to the server. I am really confuse as to why its not working on real device. 

## Expected Behavior
It should be sending the lat, longs to the server as its working perfectly on the emulator.

## Actual Behavior
I accept the "Allow always" option and can see the notification icon in the drawer but its not sending the latitudes and longitudes on the server.

## Steps to Reproduce
1. Install the app on the emulator with Api 29 (Its working)
2. Now try the same thing on a real device and it wont send those points to the server.

**Comment by darron1217** [comment]
I guess this is related to network config.
Do you use local hosted server or public server?

And don't forget that the current location is sent when your location has changed.

**Comment by ShooterArk** [comment]
a. We are using public server. 
b. I went for a walk to test the app and it didnt upload anything on the server. The same library (the main one) was working before.

**Comment by darron1217** [comment]
What's your real device's android version?

**Comment by darron1217** [comment]
Would you share your config?

**Comment by ShooterArk** [comment]
Here is the config:

"dependencies": {
    "@darron1217/react-native-background-geolocation": "^0.6.4",
    "moment": "^2.24.0",
    "native-base": "^2.13.5",
    "react": "16.8.6",
    "react-content-loader": "^5.1.0",
    "react-native": "0.60.5",
    "react-native-barcode-mask": "^1.1.0",
    "react-native-calendars": "^1.220.0",
    "react-native-camera": "^3.7.2",
    "react-native-easy-content-loader": "^0.3.2",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.26.1",
    "react-native-maps-directions": "^1.7.3",
    "react-native-modals": "^0.19.8",
    "react-native-onesignal": "^3.6.2",
    "react-native-open-maps": "^0.3.4",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-svg": "^11.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.0",
    "react-navigation-drawer": "^2.4.1",
    "react-navigation-stack": "^1.5.3",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-saga": "^1.0.5",
    "redux-thunk": "^2.3.0",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0"
  },

**Comment by darron1217** [comment]
@ShooterArk Oh, I meant the config below
https://github.com/darron1217/react-native-background-geolocation#configureoptions-success-fail

**Comment by ShooterArk** [comment]
My apologies, here you go:

> desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
          stationaryRadius: 50,
          distanceFilter: 50,
          notificationTitle: 'Background tracking',
          notificationText: 'enabled',
          notificationsEnabled: false,
          debug: false,
          startOnBoot: true,
          stopOnTerminate: true,
          locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
          interval: 5000,
          fastestInterval: 3000,
          activitiesInterval: 5000,
          stopOnStillActivity: false,
          url: "http://sts-server.herokuapp.com/api/driver/geolocation",
          httpHeaders: {
            'CONTENT-TYPE': 'application/json',
          },
          // customize post properties
          postTemplate: {
            Latitude: '@latitude',
            Longitude: '@longitude',
            Nic: this.state.nic,
            date: this.state.date
          }

**Comment by ShooterArk** [comment]
Any advise?

**Comment by darron1217** [comment]
Your config seems normal.
You can check whether the request is sending or not by `network profiler` on Android Studio.
https://developer.android.com/studio/profile/network-profiler

**Comment by darron1217** [comment]
I found that targeting SDK above 29 was not working.
Please update plugin to `0.6.6`.

**Comment by ShooterArk** [comment]
Okay let me check it out.
