### ISSUE TITLE
Android 10 and API 29 didn't update location

### ISSUE THREAD

**Issue by sami3898** [darron1217/react-native-background-geolocation#6]
Environment

* Plugin version: 0.6.4
* Platform: Android
* OS version: Android 10
* API Level: 29
* react-native-cli: 2.0.1
* react-native: 0.63.4

I have installed your library for background Location it seems working fine on Android API Level 28 but in API Level 29 it got stuck after one location return.
Also I've added BACKGROUND_LOCATION permission and ACTIVITY_RECOGNATION in Android Manifest file
but still, this issue occurred!!!

## Expected Behavior
Seems to Update Location every Second

## Actual Behavior
Not updating Location

## Possible Fix
I didn't find any fix yet

## Steps to Reproduce

1. Install Library 
2. Config Background Location Lib
3. Run it on Android with API Level 29

**Comment by darron1217** [comment]
This plugin doesn't send location every second by default.
The `distance filter` checks the distance you move, and send location when you move specific distance.
But also you  can use `interval` option to send it every second.

**Comment by darron1217** [comment]
I found that targeting SDK above 29 was not working.
Please update plugin to `0.6.6`.
