### ISSUE TITLE
Question: do I need ACCESS_BACKGROUND_LOCATION for Android >= 10?

### ISSUE THREAD

**Issue by walterdl** [darron1217/react-native-background-geolocation#8]
## Your Environment

* Plugin version: latests
* Platform: Android
* OS version: android >= 10
* Device manufacturer and model: any

* Running in Simulator: No
* React Native version: ^0.63.4
* Plugin configuration options: N/A
* Link to your project: N/A

## Context

This is just a question. I'm wanting help.

¿Do I need to set the ACCESS_BACKGROUND_LOCATION in my AndroidManifest.xml to get background location in Android >= 10? If so, ¿Could I request such permission myself instead of the library do it automatically?

**Thanks for the library!**

## Expected Behavior

N/A

## Actual Behavior

N/A

## Steps to Reproduce

N/A

## Context

N/A

## Debug logs

N/A

**Comment by darron1217** [comment]
We don't need `ACCESS_BACKGROUND_LOCATION` permission for this plugin.
It was my mistake to add it on version `0.6.4`~`0.6.5`.
And this plugin automatically requests permission.

The reason is described here. (This plugin actually uses `foreground service` on Android to do background tasks)
https://github.com/darron1217/react-native-background-geolocation#android-background-service-issues

**Comment by walterdl** [comment]
> And this plugin automatically requests permission.

Could I request the permissions by myself in some way? Because I would like to request permission just when the user will use the feature related to location tracking.

**Comment by walterdl** [comment]
> ~Could I request the permissions by myself in some way? Because I would like to request permission just when the user will use the feature related to location tracking.~

Nevermind, I saw that by invoking the `start` method the lib requests permission, so I will call it in my "start location tracking" button.

Thanks!

**Comment by darron1217** [comment]
Great :)
I'm closing this issue

**Comment by walterdl** [comment]
@darron1217 maybe you know if I need to accomplish the [Permissions Declaration Form](https://support.google.com/googleplay/android-developer/answer/9799150) guidance in order to publish an app that uses this library?

I'm not sure that despite getting the user location in a foreground service I need follow such rules.

**Comment by darron1217** [comment]
@walterdl If you have installed latest version `0.6.6`, then you don't need to write the form.

But I found that google checks every latest releases of every channels (beta, alpha... etc) to check whether this app uses background behavior or not.
So make sure that your binary is updated on every channel.

**Comment by walterdl** [comment]
Thanks a lot for your answer.

By "make sure that your binary is updated on every channel" you mean to be sure that I have the `0.6.6` installed in each apks uploaded in each channel that uses the library? but ignoring apks that don't have the library installed, like previous releases in my store. Right?

**Comment by walterdl** [comment]
Also please notice that my `targetSdkVersion` is `29`

**Comment by darron1217** [comment]
@walterdl Right. You don't need to update it if your binary is not using background permission.
